---
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  when: ansible_os_family == "Debian"

- name: Ensure linux admin packages are available
  ansible.builtin.package:
    name:
      - colordiff
      - htop
      - iftop
      - iotop
      - jq
      - mlocate
      - nano
      - ncdu
      - tldr
      - unzip
      - vim
      - zip
    state: latest

- name: Ensure linux admin packages are available (Debian Family)
  ansible.builtin.apt:
    name:
      - mailutils
      - neofetch
      - lynx
    state: latest
  when: ansible_os_family == "Debian"

- name: Ensure linux admin packages are available (Ubuntu)
  ansible.builtin.apt:
    name:
      - glances
      - lynx
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Ensure linux admin packages are available (Ubuntu 22.04)
  ansible.builtin.apt:
    name:
      - duf
    state: latest
  when: ansible_distribution == "Ubuntu" and ansible_distribution_release == "jammy"

- name: Ensure dnf package manager is installed. (RedHat Family)
  ansible.builtin.yum:
    name:
      - dnf
    state: latest
  when: ansible_os_family == "RedHat"

- name: Ensure linux admin packages are available (RedHat Family)
  ansible.builtin.dnf:
    name:
      - mailx
    state: latest
  when: ansible_os_family == "RedHat"

- name: Ensure linux admin packages are available (RedHat 7 Family)
  ansible.builtin.dnf:
    name:
      - lynx
    state: latest
  when: ansible_os_family == "RedHat" and ansible_distribution_version == "7"

- name: Ensure linux admin packages are available (RedHat 8 Family)
  ansible.builtin.dnf:
    name:
      - neofetch
      - glances
    state: latest
  when: ansible_os_family == "RedHat" and ansible_distribution_version == "8"

- name: Ensure vimrc.local is set (Debian Family)
  ansible.builtin.copy:
    src: "vimrc.local"
    dest: "/etc/vim/vimrc.local"
    mode: 0644
    owner: root
  when: ansible_os_family == "Debian"

- name: Ensure vimrc.local is set (RedHat Family)
  ansible.builtin.copy:
    src: "vimrc.local"
    dest: "/etc/vimrc"
    mode: 0644
    owner: root
  when: ansible_os_family == "RedHat"

- name: Ensure date and time added to history
  ansible.builtin.lineinfile:
    path: "/etc/profile"
    line: 'export HISTTIMEFORMAT="%d/%m/%y %T "'
    state: present

- name: Ensure .bash_aliases is set
  ansible.builtin.copy:
    src: ".bash_aliases"
    dest: "~/.bash_aliases"
    mode: 0644
    owner: root
